name: release

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release type"
        required: true
        default: "patch"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python-semantic-release
        run: pip install python-semantic-release
      - name: Release
        env:
          REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: semantic-release publish --${{ github.event.inputs.release }} -v DEBUG
